version: "3.3"
services:
  # Metrics store
  influxdb:
    image: influxdb:latest
    container_name: cb-apigw-influxdb
    ports:
      - "8083:8083"
      - "8086:8086"
    env_file:
      - './conf/env.influxdb'
    volumes:
      - ./data/influxdb/data:/var/lib/influxdb

  # Metrics UI
  grafana:
    image: grafana/grafana
    container_name: cb-apigw-grafana
    ports:
      - "3100:3000"
    depends_on:
      - influxdb
    env_file:
      - './conf/env.grafana'
    links:
      - influxdb
    volumes:
      - ./data/grafana/data:/var/lib/grafana
      - ./data/grafana/provisioning:/etc/grafana/provisioning
    user: "0"

  # Trace store and UI
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: cb-apigw-jaeger
    ports:
      - "14268:14268"
      - "16686:16686"

  # Fake API
#  fake_api:
#    image: jaxgeller/lwan
#    container_name: fake_api
#    volumes:
#      - ./data/lwan:/lwan/wwwroot
#    ports:
#      - "8100:8080"

  # HMAC Server
#  hmac_site:
#    build:
#      context: ./web
#    container_name: hmac_server
#    volumes:
#      - ./web/public:/app/public
#      - ./web/conf:/app/conf
#    ports:
#      - "8010:8010"

  # CB-SPIDER
  cb-spider:
    image: cloudbaristahub/cb-spider:v0.1-20200319
    container_name: cb-spider
    ports:
      - "1024:1024"
    volumes:
      - ./data/cb-spider:/root/go/src/github.com/cloud-barista/cb-spider/meta_db/dat
    depends_on:
      - cb-restapigw


  # CB-TUMBLEBUG
  cb-tumblebug:
    image: cloudbaristahub/cb-tumblebug:v0.1-20200313
    container_name: cb-tumblebug
    ports:
      - "1323:1323"
    depends_on:
      - cb-restapigw
      - cb-spider
    volumes:
      - ./data/cb-tumblebug:/app/meta_db/dat
    environment:
      - SPIDER_URL=http://cb-restapigw:8000/spider

# The priority used by Compose to choose which env var value to use:
# 1. Compose file
# 2. Shell environment variables
# 3. Environment file
# 4. Dockerfile
# 5. Variable is not defined

  # CB-RESTAPIGW SERVICE
  cb-restapigw:
    image: cloudbaristahub/cb-restapigw:v0.1-20200312
    container_name: cb-restapigw
    volumes:
      - ./conf/cb-restapigw:/app/conf
    ports:
      - "8000:8000"
    depends_on:
      - influxdb
      - grafana
      - jaeger
#     - hmac_site
#     - fake_api
#     - cb-spider
#     - cb-tumblebug
#
# cb-restapigw:
#   image: nginx
#   container_name: cb-restapigw
#   ports:
#     - "8000:8000"
#   volumes:
#     - ./nginx.conf:/etc/nginx/conf.d/cb-restapigw.conf:ro
