apiVersion: v1
kind: Service
metadata:
  name: {{ include "cloud-barista.fullname" . }}
  labels:
    {{- include "cloud-barista.labels" . | nindent 4 }}
spec:
  type: {{ .Values.cb_spider.service.type }}
  ports:
    - port: {{ .Values.cb_spider.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "cloud-barista.selectorLabels" . | nindent 4 }}
